return {
    { "catppuccin/nvim",
        name = "catppuccin",
        priority = 1000,
        lazy = false,
        opts = {
            flavour = "macchiato",
            integrations = {
                bufferline = true, gitsigns = true, harpoon = true,
                illuminate = { enabled = false },
                lsp_trouble = true, mason = true,
                mini = { enabled = true }, notify = false,
                telescope = { enabled = true }, treesitter = true,
                which_key = true,
            },
        },
        config = function(_, opts)
            require("catppuccin").setup(opts)
            vim.cmd.colorscheme("catppuccin")
        end,
    },
    { "akinsho/bufferline.nvim",
        version = "*",
        dependencies = { "nvim-tree/nvim-web-devicons" },
        opts = {
            options = {
                mode = "buffers",
                diagnostics = false,
                show_buffer_close_icons = false,
                show_close_icon = false,
                separator_style = "thin",
            },
        },
    },
    { "nvim-lualine/lualine.nvim",
        lazy = false,
        priority = 999,
        dependencies = { "catppuccin/nvim" },
        opts = {
            options = {
                theme = "auto",
                globalstatus = true,
                section_separators = "",
                component_separators = "|",
            },
            sections = {
                lualine_a = { "mode" },
                lualine_b = { "branch", "diff" },
                lualine_c = { { "filename", path = 1 } },
                lualine_x = { "filetype" },
                lualine_y = {},
                lualine_z = { "location" },
            },
        },
    },
    { "lewis6991/gitsigns.nvim", opts = {} },
    { "folke/snacks.nvim",
        priority = 1000,
        lazy = false,
        opts = {
            notifier = { enabled = true },
            bigfile      = { enabled = false },
            dashboard    = { enabled = false },
            indent       = { enabled = false },
            input        = { enabled = false },
            picker       = { enabled = false },
            quickfile    = { enabled = false },
            scroll       = { enabled = false },
            statuscolumn = { enabled = false },
            words        = { enabled = false },
        },
    },
    { "folke/which-key.nvim",
        opts = {
            win = { height = { min = 3, max = 8 } },
            spec = {
                { "<leader>s", group = "Search" },
                { "<leader>f", group = "Format" },
                { "<leader>p", group = "Pins", icon = { icon = "󰐃", color = "cyan" } },
                { "<leader>r", group = "Rails" },
                { "<leader>d", group = "Diagnostics" },
                { "<leader>i", group = "Info" },
                { "<leader>l", group = "Lazy" },
                { "<leader>h", group = "Help" },
                { "<leader>g", icon = { icon = "󰊢", color = "red" } },
                { "<leader>Y", hidden = true },
                { "<leader>P", hidden = true },
                { "gz", group = "Surround" },
                { "[",  group = "Prev" },
                { "]",  group = "Next" },
                { "a",  group = "Around", mode = { "o", "x" } },
                { "i",  group = "Inside", mode = { "o", "x" } },
            },
        },
    },
}
