return {
    { "catppuccin/nvim",
        name = "catppuccin",
        priority = 1000,
        lazy = false,
        opts = {
            flavour = "macchiato",
            integrations = {
                bufferline = true, gitsigns = true, harpoon = true,
                illuminate = { enabled = false },
                lsp_trouble = true, mason = true,
                mini = { enabled = true }, notify = true,
                telescope = { enabled = true }, treesitter = true,
                which_key = true,
            },
        },
        config = function(_, opts)
            require("catppuccin").setup(opts)
        end,
    },
    { "folke/tokyonight.nvim", lazy = false, priority = 1000 },
    { "rebelot/kanagawa.nvim", lazy = false, priority = 1000 },
    { "ellisonleao/gruvbox.nvim", lazy = false, priority = 1000 },
    { "rose-pine/neovim", name = "rose-pine", lazy = false, priority = 1000 },
    { "navarasu/onedark.nvim", lazy = false, priority = 1000 },
    { "EdenEast/nightfox.nvim", lazy = false, priority = 1000 },
    { "sainnhe/everforest", lazy = false, priority = 1000 },
    { "Mofiqul/dracula.nvim", lazy = false, priority = 1000 },
    { "projekt0n/github-nvim-theme", lazy = false, priority = 1000 },
    { "akinsho/bufferline.nvim",
        version = "*",
        dependencies = { "nvim-tree/nvim-web-devicons" },
        opts = {
            options = {
                mode = "buffers",
                diagnostics = false,
                show_buffer_close_icons = false,
                show_close_icon = false,
                separator_style = "thin",
            },
        },
    },
    { "nvim-lualine/lualine.nvim",
        lazy = false,
        priority = 999,
        dependencies = { "catppuccin/nvim" },
        opts = {
            options = {
                theme = "auto",
                globalstatus = true,
                section_separators = "",
                component_separators = "|",
            },
            sections = {
                lualine_a = { "mode" },
                lualine_b = { "branch", "diff" },
                lualine_c = { { "filename", path = 1 } },
                lualine_x = { "filetype" },
                lualine_y = {},
                lualine_z = { "location" },
            },
        },
    },
    { "lewis6991/gitsigns.nvim", opts = {} },
    { "rcarriga/nvim-notify",
        lazy = false,
        opts = {
            stages = "static",
            timeout = 3000,
            max_width = 60,
        },
        config = function(_, opts)
            local notify = require("notify")
            notify.setup(opts)
            vim.notify = notify
        end,
    },
    { "folke/which-key.nvim",
        opts = {
            win = { height = { min = 3, max = 8 } },
            spec = {
                { "<leader>s", group = "Search" },
                { "<leader>p", group = "Pins", icon = { icon = "󰐃", color = "cyan" } },
                { "<leader>d", group = "Diagnostics" },
                { "<leader>i", group = "Info" },
                { "<leader>t", group = "Toggle" },
                { "<leader>l", group = "Lazy" },
                { "<leader>g", icon = { icon = "󰊢", color = "red" } },
                { "<leader>Y", hidden = true },
                { "<leader>P", hidden = true },
                { "gz", group = "Surround" },
                { "[",  group = "Prev" },
                { "]",  group = "Next" },
                { "a",  group = "Around", mode = { "o", "x" } },
                { "i",  group = "Inside", mode = { "o", "x" } },
            },
        },
    },
}
